import '../styles/global.scss';
import Head from 'next/head';

function MyApp({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>Todo app</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />{' '}
      </Head>
      <Component {...pageProps} />
    </>
  );
}

export default MyApp;
