import '../styles/global.scss';
import Head from 'next/head';
import { AuthProvider } from '../lib/auth';
function MyApp({ Component, pageProps }) {
  return (
    <AuthProvider>
      <Head>
        <title>Todo app</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />{' '}
      </Head>
      <Component {...pageProps} />
    </AuthProvider>
  );
}

export default MyApp;
