/** @jsxImportSource @emotion/react */
import { jsx } from '@emotion/react';
import { css } from '@emotion/react';
import Header from '../components/header/header';
import MainSec from '../components/MainSection/mainSection';
import { useAuth } from '../lib/auth';
import Head from 'next/head';
import {
  btnWrapper,
  signInTitle,
  githubBtn,
  gmailBtn,
} from '../components/login/login.css';
import { Git } from '../components/icons/githubLogo';

export default function Home() {
  const auth = useAuth();
  if (!auth.user) {
    return (
      <>
        <div
          css={css`
            padding: 1rem 5rem;
            display: flex;
            justify-content: space-between;
            align-items: center;
            @media (max-width: 450px) {
              padding: 1rem;
            }
          `}
        >
          <span
            css={css`
              text-transform: uppercase;
              color: var(--text);
              letter-spacing: 2px;
              font-weight: bold;
              font-size: 1.5rem;
            `}
          >
            todo
          </span>
          <a
            href="http://github.com/zineb-bou"
            aria-label="Link to github repo"
            target="_blank"
            rel="noreferrer"
          >
            <Git />
          </a>
        </div>
        <div css={btnWrapper}>
          <h2 css={signInTitle}>Sign in</h2>
          <button
            css={githubBtn}
            onClick={(e) => {
              auth.signinWithGitHub();
            }}
          >
            Login with Github
          </button>
          <button
            css={gmailBtn}
            onClick={(e) => {
              auth.signinWithGoogle();
            }}
          >
            Login with Gmail
          </button>
        </div>
      </>
    );
  }
  return (
    <>
      <Head>
        <title>Todo app</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />{' '}
      </Head>
      <Header />
      <MainSec />
      <footer
        css={css`
          margin: 50px 0;
          display: grid;
          place-items: center;
          color: var(--text);
        `}
      >
        <p>Drag and drop to reorder list</p>
        <p>
          Made with ❤️ by
          <a
            href="https://github.com/zineb-Bou"
            css={css`
              text-decoration: none;
              color: var(--Check-BG-end);
            `}
          >
            {' '}
            Zineb Boutaa
          </a>
        </p>
      </footer>
    </>
  );
}
